### ISSUE TITLE
feature request: MaterialTags

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/PaperLib#10]
can it be possible to add this https://papermc.io/javadocs/com/destroystokyo/paper/MaterialTags.html so that spigot/paper can be used

**Comment by aikar** [comment]
@PhanaticD eh, that references 1.13 API, but outside of that nothing stops you from copying my code into your own plugin

I don't want to maintain that list in 2 places. just going to recommend duping it into your plugin instead.
