### ISSUE TITLE
Add PlayerProfile support

### ISSUE THREAD

**Issue by NickAcPT** [PaperMC/PaperLib#18]
My request is to add support for PlayerProfile for players and skulls.

**Comment by wizjany** [comment]
What would the fallback be...?

**Comment by NickAcPT** [comment]
Maybe somehow implementing it with packets and reflection.

**Comment by wizjany** [comment]
"Plugin Library for interfacing with Paper Specific API's with graceful fallback that maintains Spigot Compatibility, such as Async Chunk Loading. "
From the project description.

**Comment by NickAcPT** [comment]
Yes, I know that. The PlayerProfile API is Paper specific.

**Comment by wizjany** [comment]
right, the point is there's no graceful fallback. if you want to do hacky reflection/packets/whatever that's best done in your own plugin.

**Comment by NickAcPT** [comment]
Oh, I see. Closing this.
