### ISSUE TITLE
TNT

### ISSUE THREAD

**Issue by TheWackersKian** [PaperMC/PaperLib#32]
Hi there! I am currently experiencing an issue on 1.16.2 Paper where when TNT explodes blocks, the items don't actually drop. I have tested this on multiple occasions but unfortunately no luck.
[video.zip](https://github.com/PaperMC/PaperLib/files/5180378/video.zip)

**Comment by Chew** [comment]
Hello, this appears to be an issue with Paper, please [report an issue there](https://github.com/PaperMC/Paper/issues/new/choose) and fill out the template. Thank you!
