### ISSUE TITLE
teleportAsync not teleporting other dimensions when called asynchronously

### ISSUE THREAD

**Issue by Sneakometer** [PaperMC/PaperLib#34]
Calling PaperLib.teleportAsync(entity, location) from outside of the main thread causes it to not work when the target location is in another dimension/world than the entity to be teleported.
Expereincing this on paper 1.12.2 using PaperLib 1.0.6.

**Comment by BillyGalbreath** [comment]
Can you replicate this on latest build of 1.16.4? If yes, we can fix it for 1.16.4, but 1.12.2 is unsupported and will receive no backports

**Comment by Proximyst** [comment]
> from outside of the main thread

Won't fix. You should call the method on the main thread; the teleport itself is however asynchronous (which does not necessarily mean threaded on another thread!) and may happen in the future (hence the `CompletableFuture` returned).
