### ISSUE TITLE
PaperLib 1.8 Suggest Paper

### ISSUE THREAD

**Issue by Jaimss** [PaperMC/PaperLib#38]
I am using PaperLib for one of my plugins, and am using the `PaperLib#suggestPaper` method. Someone mentioned to me that on their 1.8 server running Paper, they were getting the suggestion to switch to paper, and I tried it out and got the same thing.

### Steps to Reproduce
- Download 1.8.8 Paper ([here](https://papermc.io/legacy))
- Make a quick plugin with spigot as the dependency, and paper lib shaded
- Call the suggest paper method on startup.

I am assuming that the class used just didn't exist in 1.8.8, but is there a class that does exist across all versions that could be used instead?

**Comment by yannicklamprecht** [comment]
It's likely that the PaperConfig wasn't located or named how it is today. So I see no problems here, especially because paperspigot isn't supported anymore. The recommendation to use Paper is perfectly fine.

**Comment by notOM3GA** [comment]
its because 1.8 had a different class name so it can only tell it is running on a "PaperSpigot" server, not Paper
