### ISSUE TITLE
java.lang.NoSuchMethodError: org.bukkit.block.Block.isSolid()Z

### ISSUE THREAD

**Issue by SashaSemenishchev** [PaperMC/PaperLib#39]
When I call block.isSolid - error: java.lang.NoSuchMethodError: org.bukkit.block.Block.isSolid()Z

**Comment by Proximyst** [comment]
Wrong repo. Update. https://github.com/PaperMC/Paper/commit/7bfb781ff31b88e39a7f0116341ee3edbe5d6041
