### ISSUE TITLE
old combat

### ISSUE THREAD

**Issue by LeBaasti** [PaperMC/PaperLib#50]
Hey,
I have a question about old combat.
Is it possible to add a feature in the config to activate the old combat(1.8) like knockback etc.
in server version like 1.16?

Best regards
LeBaasti

**Comment by electronicboy** [comment]
Issue trackers are for issues, we are not here to provide support or act like google, etc
This is also still the wrong issue tracker for an actual server issue

**Comment by LeBaasti** [comment]
ok, sorry
