### ISSUE TITLE
ClassNotFound Exception

### ISSUE THREAD

**Issue by dorrzun** [PaperMC/PaperLib#60]
Hi there!

I'm trying to test this library's Spigot functionality, but when I call PaperLib.getChunkAtAsync(world,x,z), an exception is thrown.
I have the Maven dependency added through IntelliJ, and am running a regular Spigot server.

Am I missing something here?

**Comment by HexedHero** [comment]
Are you shading the library into your plugin jar?

**Comment by electronicboy** [comment]
You need to bundle paperlib into your own jar, please see the readme
