### ISSUE TITLE
can't initialize database on M1

### ISSUE THREAD

**Issue by xdchen2** [PaperMC/PaperLib#61]
It takes forever to initialize the database so that I can;t add tags or folders

**Comment by electronicboy** [comment]
what?

**Comment by electronicboy** [comment]
Logs? info? Literally never heard of that one before

**Comment by mrfloris** [comment]
Do you have steps for me to try and reproduce this?

**Comment by xdchen2** [comment]
Sorry I guess it’s because this was the first time I opened the app. I don’t have logs as I use the binary installation. I tried a second time, and it works now. BTW: I have a new problem. Some of the papers can;t be added as the way the app rename the file exceeds the length limit. Is there a way to change this?

On Jun 24, 2022, at 11:39, Shane Freeder ***@***.******@***.***>> wrote:



Logs? info? Literally never heard of that one before

**Comment by electronicboy** [comment]
PaperLib is not an app, I have no ide what you're going on about but it sounds 100% irrelevant to us
