### ISSUE TITLE
Current Maintenance Status of PaperLib

### ISSUE THREAD

**Issue by MajdT51** [PaperMC/PaperLib#68]
Hello,

I've been using the library and it’s been really helpful. I'm maintaining another plugin that could use it, but I noticed there haven’t been updates for a while. I would like to ask if the project still active?

Thanks for any info you can provide!

Best,
Majd

**Comment by MiniDigger** [comment]
is there something that is broken that would need an update?

**Comment by MajdT51** [comment]
> is there something that is broken that would need an update?

No everything works well :) great job and thank you. I just wanted to make sure that someone is looking :D before using it again in another plugin

**Comment by MiniDigger** [comment]
we are looking :)
